spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_authservice_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Quan2004@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    serverUrl: http://localhost:${server.port}
    serverName: Server Dev
    title: API Document
    version: 1.0.0
server:
  port: 8010
