spring.application.name=FinalProject
#server.port = 8083
#spring.profiles.active=dev
##
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=Unknown
#spring.datasource.password=Drsunknown
#spring.datasource.url=jdbc:mysql://localhost:3306/em
#
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

#default is 10
spring.profiles.active=dev
spring.datasource.hikari.maximum-pool-size=10
#default is same as max pool size
spring.datasource.hikari.minimum-idle=10
#default is 30 seconds
spring.datasource.hikari.connection-timeout=30000
#default is 600000 i.e 10 minutes
spring.datasource.hikari.idle-timeout=600000
#default is 1800000 i.e 30 minutes
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariConnPool

payos.client_id = ${PAYOS_CLIENT_ID}

payos.api-key = ${PAYOS_KEY}

payos.checksum-key = ${PAYOS_CHECKSUM_KEY}


cloudinary.keyname = ${CLOUDINARY_KEYNAME}

cloudinary.api_key = ${CLOUDINARY_API-KEY}

cloudinary.api_secret = ${CLOUDINARY_API-SECRET}

spring.mail.host=smtp.gmail.com

spring.mail.port=${MAIL_PORT}

spring.mail.username=${MAIL_USER}

spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

frontend.url=${FRONTEND_URL}